# Generated by Django 5.0.6 on 2024-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_address_alter_user_image_alter_user_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='', null=True, upload_to='users_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(blank='', null=True),
        ),
    ]
