# Generated by Django 5.0.6 on 2024-06-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0005_alter_user_address_alter_user_image_alter_user_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
    ]
