# Generated by Django 5.0.6 on 2024-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0006_remove_user_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank='', null=True, upload_to='user_images'),
        ),
    ]
